### PR TITLE
Implemented animation for started build state

### PR DESCRIPTION
**Pull request by DreierF**
As discussed in #25 here the implementation of the started animation

### CODE REVIEW

**Comment by dkhmelenko** [comment]
@DreierF  The app is crashing after I restarted the build. And during the time build is in progress, it's impossible to launch the app, it crashes all the time.
Device Galaxy S7 edge (Android, 6.0). Here is stacktrace:
```
FATAL EXCEPTION: main
                                                                                Process: com.khmelenko.lab.travisclient, PID: 25829
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.graphics.drawable.VectorDrawableCompat.setAllowCaching(boolean)' on a null object reference
                                                                                    at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:378)
                                                                                    at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:168)
                                                                                    at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:148)
                                                                                    at com.khmelenko.lab.travisclient.converter.BuildStateHelper.getBuildImage(BuildStateHelper.java:72)
                                                                                    at com.khmelenko.lab.travisclient.adapter.RepoListAdapter.onBindViewHolder(RepoListAdapter.java:56)
                                                                                    at com.khmelenko.lab.travisclient.adapter.RepoListAdapter.onBindViewHolder(RepoListAdapter.java:29)
                                                                                    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                                    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                    at android.view.View.layout(View.java:17938)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
```

**Comment by DreierF** [comment]
OK. I'll take a look as soon as I find some time for it.

**Comment by DreierF** [comment]
Could you please check if this fixes the issues you had on your phone as well?

**Comment by dkhmelenko** [comment]
I will check PR on this weekend

**Comment by DreierF** [comment]
Hmm. It's definitely a device specific issue, because it works perfectly fine on my Nexus 6P.
Could you uncomment the other states except STARTED in BuildStateHelper.getBuildImage to make sure it's not an issue with the state.
Otherwise I could try to debug it next week on my aunt's Galaxy S7...

**Comment by dkhmelenko** [comment]
It's not state issue, I checked. State is set up properly. 

When I restared the app, I was able to see the animation. So it's not device specific issue.

**Comment by DreierF** [comment]
Ok great! So how can I reproduce the issue?

**Comment by dkhmelenko** [comment]
Go to any buid and press button restart from build details. You will see that animation doesn't start immediately. If you press button back, animation will not be shown also.
When you close the app and launch it again, then you will see animation of the build in progress.

**Comment by DreierF** [comment]
And you are really sure that the state is already set to STARTED before you restart the app? Because in CREATED state the icon is shown without animation and it takes some time until Travis enters the STARTED state. And as far as I remember the app does not yet requery the state of the build automatically, does it?

**Comment by dkhmelenko** [comment]
ah, true! sorry, my mistake, I was checking state color, but not the text. In CREATED there is not animation, but there is animation in STARTED.
Perfect! 👏  This PR will be merged soon!

**Pull request merged**
